config/routes.rb
Georgia::Engine.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, class_name: "Georgia::User", path: '', module: 'georgia/users', path_names: {sign_in: 'login', sign_out: 'logout'}

  namespace :api do
    resources :media, only: [] do
      collection do
        get :pictures
      end
    end
    resources :tags, only: [:index] do
      get :search, on: :collection
    end
  end

  Georgia::PageableRouteConcern.included(self)

  resources :pages, concerns: [:pageable]

  resources :media, path: :media do
    collection do
      get :search
      post :download
      delete '/', to: :destroy
    end
  end
  resources :users do
    get 'permissions', on: :collection
  end
  resources :menus, path: 'navigation'
  resources :links, only: [:create, :show]
  resources :widgets
  resources :ui_associations, path: 'ui-associations', only: [:new]
  resources :slides, only: [:new]

  # unauthenticated do
  #   as :user do
  #     root to: 'users/sessions#new'
  #   end
  # end
  root to: "dashboard#show"

end

app/models/georgia/revision.rb
module Georgia
  class Revision < ActiveRecord::Base

    include PublicActivity::Common
    include Concerns::Contentable

    enum status: [ :draft, :review, :published, :revision ]

    belongs_to :user, foreign_key: :revised_by_id

    has_one :page, foreign_key: :revision_id
    belongs_to :revisionable, polymorphic: true, touch: true

    has_many :slides, dependent: :destroy, foreign_key: :page_id
    accepts_nested_attributes_for :slides, allow_destroy: true

    has_many :ui_associations, dependent: :destroy, foreign_key: :page_id
    accepts_nested_attributes_for :ui_associations, allow_destroy: true

    has_many :widgets, through: :ui_associations

    validates :template, inclusion: {in: Georgia.templates, message: "%{value} is not a valid template" }

    delegate :visibility, to: :revisionable, prefix: false

  end
end

app/controllers/georgia/revisions_controller.rb
module Georgia
  class RevisionsController < ApplicationController

    before_filter :prepare_revision, except: :index
    before_filter :prepare_page, only: :index
    before_filter :prepare_content, only: [:edit, :update]

    def index
      @revisions = @page.revisions.order(created_at: :desc)
      authorize @revisions
    end

    def show
      authorize @revision
      redirect_to edit_page_revision_path(@page, @revision)
    end

    def edit
      authorize @revision
      locale = params.fetch(:locale, current_locale)
      @activities = (@page.activities + @revision.activities).uniq.sort_by(&:created_at).reverse
      @slides = @revision.slides.ordered.with_locale(locale)
      @ui_sections = Georgia::UiSection.all
      @status_message = RevisionStatusMessage.new(current_user, @page, @revision)
      @awaiting_revisions = @page.revisions.where(status: Georgia::Revision.statuses[:review])
      @draft_revision = @page.revisions.where.not(id: @revision.id).where(user: current_user).where(status: [Georgia::Revision.statuses[:review], Georgia::Revision.statuses[:draft]]).first
    end

    # Stores a copy of the current revision before updating
    def update
      authorize @revision
      update_with_service do |service|
        service_object = service.new(current_user, @page, @revision, sanitized_attributes)
        if service_object.call
          CreateActivity.new(@revision, :update, owner: current_user).call
          redirect_to edit_page_revision_path(@page, service_object.revision), notice: "#{service_object.revision.title} was successfully updated."
        else
          redirect_to edit_page_revision_path(@page, @revision), alert: service_object.revision.errors.full_messages.join('. ')
        end
      end
    end

    def destroy
      authorize @revision
      # FIXME: Check if this is the last revision for the page. Can't delete the last revision.
      if @revision.destroy
        redirect_to [:edit, @page], notice: "Revision was successfully deleted."
      else
        redirect_to page_revisions_path(@page), alert: "Oups! Something went wrong."
      end
    end

    # Sends revision to main_app router
    # FIXME: bypass this once Georgia will be loaded on root
    def preview
      authorize @page
      redirect_to preview_url
    end

    def draft
      authorize @revision
      ensure_remove_previous_drafts_of_the_same_page
      if @draft = Georgia::CloneRevision.create(@revision, status: 'draft', revised_by_id: current_user.id)
        CreateActivity.new(@draft, :draft, owner: current_user).call
        redirect_to edit_page_revision_path(@page, @draft), notice: "You successfully created a new draft."
      else
        redirect_to edit_page_revision_path(@page, @revision), alert: "Oups! Something went wrong."
      end
    end

    def request_review
      authorize @revision
      if @revision.update(status: :review)
        CreateActivity.new(@revision, :review, owner: current_user).call
        notify("#{current_user.name} is asking you to review #{@revision.title}.", edit_page_revision_path(@page, @revision, only_path: false))
        redirect_to edit_page_revision_path(@page, @revision), notice: "You successfully submited #{@revision.title} for review."
      else
        redirect_to edit_page_revision_path(@page, @revision), alert: "Oups! Something went wrong."
      end
    end

    def approve
      authorize @revision
      if @revision.update(status: :published)
        @page.current_revision.update(status: :revision)
        @page.update(revision_id: @revision.id)
        CreateActivity.new(@revision, :approve, owner: current_user).call
        redirect_to edit_page_revision_path(@page, @revision), notice: "You have successfully approved and published #{@revision.title}."
      else
        redirect_to edit_page_revision_path(@page, @revision), alert: "Oups! Something went wrong."
      end
    end

    def decline
      authorize @revision
      if @revision.update(status: :draft)
        CreateActivity.new(@page, :decline, owner: current_user).call
        message = "#{current_user.name} has successfully declined a review for #{@revision.title}."
        @revision.destroy
        redirect_to [:edit, @page], notice: message
      else
        redirect_to edit_page_revision_path(@page, @revision), alert: "Oups! Something went wrong."
      end
    end

    def restore
      authorize @revision
      if @revision.update(status: :published)
        @page.current_revision.update(status: :revision)
        @page.update(revision_id: @revision.id)
        CreateActivity.new(@revision, :restore, owner: current_user).call
        redirect_to @page, notice: "#{current_user.name} has successfully restored a previous revision for #{@revision.title}."
      else
        redirect_to page_revisions_path(@page), alert: "Oups! Something went wrong."
      end
    end

    private

    def prepare_page
      polymorphic_resource_key = params.keys.select{|k| k.match('_id')}.first
      @page = Page.where(id: params[polymorphic_resource_key]).first
    end

    def prepare_revision
      @revision = Revision.where(id: params[:id]).first
      if @revision
        @page = @revision.try(:revisionable)
      else
        authorize Georgia::Revision
        prepare_page
        if @page
          redirect_to [:edit, @page], alert: 'This revision has been deleted or does not exist.'
        else
          redirect_to georgia.root_path, alert: "This resource has been deleted or does not exist."
        end
      end
    end

    def prepare_content
      if locale = params[:locale]
        @content = @revision.contents.select{|c| c.locale.to_s == locale}.first
        @content ||= Georgia::Content.new(locale: locale) if locale
      else
        @content = @revision.content
      end
      @content = Georgia::ContentDecorator.decorate(@content)
    end

    def notify(message, url)
      Notifier.notify_editors(message, url).deliver
    end

    def preview_url
      "#{@page.decorate.url}?r=#{@revision.id}"
    end

    def revision_params
      params.require(:revision).permit(
        :template,
        contents_attributes: [:text, :title, :locale, :excerpt, :keyword_list, :image_id, :id],
        slides_attributes: [:position, :id, :_destroy, contents_attributes: [:text, :title, :image_id, :locale, :id]],
        ui_associations_attributes: [:id, :_destroy, :position, :ui_section_id, :widget_id]
      )
    end

    def sanitized_attributes
      attributes = revision_params
      attributes.fetch(:contents_attributes, []).each do |id, content_attributes|
        attributes[:contents_attributes][id] = ParseJsonTags.new(content_attributes, key: :keyword_list).call
      end
      attributes
    end

    def update_with_service
      service = 
        if policy(@revision).publish?
          UpdateRevision::Admin
        elsif policy(@revision).draft_changes?
          UpdateRevision::Contributor
        else
          UpdateRevision::Guest
        end
      yield service
    end

    def ensure_remove_previous_drafts_of_the_same_page
      @page.revisions.where(user: current_user).where(status: [Georgia::Revision.statuses[:review], Georgia::Revision.statuses[:draft]]).destroy_all
    end

  end
end

app/views/georgia/revisions/fields/_content.html.erb
<fieldset>
  <div class="fieldset-help">
    <legend>Content</legend>
    <%= link_to_available_locales %>
  </div>
  <div class="fieldset-fields">
    <%= f.input :text, label: false, as: :ckeditor, input_html: {toolbar: 'Full'} %>
  </div>
</fieldset>
<fieldset>
  <div class="fieldset-help">
    <legend>SEO</legend>
    <p class="hint">
      The excerpt and keywords will be included as &lt;meta&gt; description and keywords tags, useful for search engines.
    </p>
  </div>
  <div class="fieldset-fields">
    <%= f.input :excerpt, as: :text, label: 'Excerpt/Description', input_html: {rows: 3}, hint: "Describe in a short paragraph what this page is about." %>
    <%= f.input :keyword_list, as: :text, label: 'Keywords', hint: "Comma-separated list of keywords, e.g. spiderman, superman, comics, superhero.", input_html: {class: 'js-taggable', row: 1} %>
  </div>
</fieldset>
<fieldset>
  <div class="fieldset-help">
    <legend>Featured Image</legend>
  </div>
  <div class="fieldset-fields">
    <%= choose_image_tag(@content, target: 'revision_content_image', input: f.hidden_field(:image_id)) %>
  </div>
</fieldset>

app/views/georgia/revisions/fields/_message.html.erb
<% if @status_message.partial or @draft_revision %>
  <fieldset>
    <div class="fieldset-help">
      <legend><%= icon_tag('exclamation-triangle', size: 'lg') %> Attention</legend>
    </div>
    <div class="fieldset-fields">
      <%= render partial: "georgia/revisions/messages/continue_draft" if @draft_revision %>
      <%= render partial: "georgia/revisions/messages/#{@status_message.partial}" if @status_message.partial %>
    </div>
  </fieldset>
<% end -%>

app/views/georgia/revisions/fields/_slides.html.erb
<fieldset>
  <div class="fieldset-help">
    <legend>Slides</legend>
    <p>
      <%= link_to "#{icon_tag 'plus'} Add slide".html_safe, '#', class: 'btn btn-primary js-add-slide' %>
    </p>
  </div>
  <div class="fieldset-fields">
    <div class="control-group">
      <div class="slides js-slides">
        <ul class="nav-list js-sortable">
          <% @slides.each do |slide| %>
            <%= slide_portlet_tag(slide, content: slide.content(params[:locale])) %>
          <% end -%>
        </ul>
      </div>
    </div>
  </div>
</fieldset>

app/views/georgia/revisions/fields/_template.html.erb
<fieldset>
  <div class="fieldset-help">
    <legend>Template</legend>
  </div>
  <div class="fieldset-fields">
    <%= f.input :template, collection: Georgia.templates, label: false %>
  </div>
</fieldset>

app/views/georgia/revisions/fields/_ui_section.html.erb
<div class="control-group input-horizontal">
  <label><%= ui_section.name %></label>
  <div class="widgets js-nested-widgets" data-ui-section="<%= ui_section.id %>" data-revision="<%= @revision.id %>">
    <ul class="nav-list js-sortable">
      <% ui_section.ui_associations.for_revision(@revision).order(:position).each do |ui_association| %>
        <%= widget_portlet_tag(ui_association) %>
      <% end -%>
    </ul>
    <div class="form-group">
      <%= select_tag :widget, widgets_collection, prompt: 'Select a widget', class: 'form-control select-widget' %>
      <%= link_to "#{icon_tag('plus')} Add".html_safe, '#', class: 'btn btn-primary js-add-widget' %>
    </div>
  </div>
</div>

app/views/georgia/revisions/fields/_widgets.html.erb
<fieldset>
  <div class="fieldset-help">
    <legend>Widgets</legend>
    <p class='hint'>
      <%= link_to "#{icon_tag('cogs')} Manage Widgets".html_safe, widgets_path, class: 'btn btn-primary' if policy(Georgia::Widget).index? %>
    </p>
  </div>
  <div class="fieldset-fields">
    <%= render partial: 'georgia/revisions/fields/ui_section', collection: @ui_sections, as: :ui_section, locals: {f: f} %>
  </div>
</fieldset>